name: 'Bootstrap Package Actions'
description: 'Bootstraps Actions to Build and Update an Action'
inputs:
  upstream:
    description: 'Upstream package Repository (sth. like https://aur.archlinux.org/autotiling.git)'
    required: false
runs:
  using: "composite"
  steps:
    - 
      name: prepare
      shell: bash
      run: |
        git config user.name bootstrap-package-actions
        git config user.email info@manjaro-sway.download
    -
      name: bootstrap
      shell: bash
      run: |
        if [[ -n "${{ inputs.upstream }}" ]]; then
          cp ${{ github.action_path }}/actions/upstream/* .github/workflows/
        fi
        cp ${{ github.action_path }}/actions/common/* .github/workflows/

        [ -f .github/dependabot.yml ] || cp ${{ github.action_path }}/dependabot.yml .github/
        
        sed -i 's|__UPSTREAM__|"${{ inputs.upstream }}"|g' .github/workflows/*.yml
    -
      name: commit
      shell: bash
      run: |
        git add .github/workflows/*.yml
        git add .github/*
        git commit -m "chore(actions-bootstrap): update default actions"
        git push