name: 'Bootstrap Package Actions'
description: 'Bootstraps Actions to Build and Update an Action'
inputs:
  upstream:
    description: 'Upstream package Repository (sth. like https://aur.archlinux.org/autotiling.git)'
    required: false
runs:
  using: "composite"
  steps:
    - name: prepare
      shell: bash
      run: |
        git config user.name bootstrap-package-actions
        git config user.email info@manjaro-sway.download
    - name: bootstrap
      shell: bash
      env:
        UPSTREAM: ${{ inputs.upstream }}
      run: |
        cp ${{ github.action_path }}/.github/workflows/* .github/workflows/
        cp ${{ github.action_path }}/.github/settings.yml .github/

        sed -i "s|__UPSTREAM__|"${UPSTREAM}"|g" .github/settings.yml
        sed -i "s|__UPSTREAM__|"${UPSTREAM}"|g" .github/workflows/*.yml

        cp -f ${{ github.action_path }}/renovate.json .
    - name: commit
      shell: bash
      run: |
        git add .github/workflows/*.yml
        git add .github/*

        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "chore(actions-bootstrap): update default actions"
          git push
        fi
        